---
description: >
 Analyse last weeks data.
docopt: >
 usage: 
  lastweek.Rmd -c <CASEFILE> -p <POSTCODEDB>

 options:
  -c <CASEFILE> CSV case file of Date and postcode
  -p <POSTCODEDB> Postcode database

output:
 pdf_document:
  toc: false
---

```{r start}
library(dplyr)
library(devtools)
load_all("../phlabr")
load_all("../UKpostcodes")
library(sf)
```

# Read Data

```{r readdata}
data = read.table(opts$c)
lcwdata = last_weeks_data(data)
summary(lcwdata)
head(lcwdata)
```

# Range of Data

```{r range}
range(lcwdata$Date)
```

# Summary By Postcode Geography

## Postcode Areas

```{r pca}
areas = table(pc_area(lcwdata$postcode))
sort(areas, dec=TRUE)
```

## Postcode District
```{r pcd}
districts = table(pc_district(lcwdata$postcode))
sort(districts, dec=TRUE)
```

## Postcode Sectors with more than 1 case
```{r pcs}
sectors = table(pc_sector(lcwdata$postcode))
big2 = sectors[sectors>1]
sort(big2, dec=TRUE)
```


# Standardized Incidence Ratio

## Postcode Areas

```{r sirarea}
areas = lcwdata %>% group_by(area=pc_area(postcode)) %>% summarise(n=n())
pc_areas = st_read(opts$p,"pc_areas")
area_data = join_to_spatial(areas, pc_areas, c("pc_area"="area"),"n")
area_data$sir = sir(area_data, "n", "pop")
area_data
plot(area_data[,"sir"],pch=19)
```

